[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Chintan Mehta"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.135.2"}
numpy = "^2.4.3"
scipy = "^1.17.1"
pydantic = "^2.12.5"
google-genai = "^1.68.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
